<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = [
            [
                "id" => "1",
                "name" => "Лолита",
                "surname" => "Холматова",
                "patronymic" => "Нажмутдиновна",
                "email" => "loliholmatova@gmail.com",
            ],
            [
                "id" => "2",
                "name" => "Шухрат",
                "surname" => "Сафаров",
                "patronymic" => "Шарофудинович",
                "email" => "hr.tjk@evolet.co.uk",
            ],
            [
                "id" => "3",
                "name" => "Нозимчон",
                "surname" => "Хакимов",
                "patronymic" => "Юнусович",
                "email" => "nozim.khakimov@evolet.co.uk",
            ],
            [
                "id" => "4",
                "name" => "Фирдавс",
                "surname" => "Киличбеков",
                "patronymic" => "Киличбекович",
                "email" => "firdavs.kilichbekov@evolet.co.uk",
            ],
            [
                "id" => "5",
                "name" => "Азимчон",
                "surname" => "Вохиди",
                "patronymic" => null,
                "email" => "vokhid.azimjon@evolet.co.uk",
            ],
            [
                "id" => "6",
                "name" => "Парвиз",
                "surname" => "Иброхимбеков",
                "patronymic" => "Джаборович",
                "email" => "parviz.pdd@evolet.co.uk",
            ],
            [
                "id" => "7",
                "name" => "Муллохасан",
                "surname" => "Тураев",
                "patronymic" => "Мирзоевич",
                "email" => "tmabstragan@gmail.com",
            ],
            [
                "id" => "8",
                "name" => "Анвар",
                "surname" => "Джаборов",
                "patronymic" => "Закирович",
                "email" => "a.dzhabarov@evolet.co.uk",
            ],
            [
                "id" => "9",
                "name" => "Джоми",
                "surname" => "Султонзода",
                "patronymic" => null,
                "email" => "jomi.sultonzoda90@gmail.com",
            ],
            [
                "id" => "10",
                "name" => "Иноятшо",
                "surname" => "Насридиншоев",
                "patronymic" => "Мирджонович",
                "email" => "ino1361@mail.ru",
            ],
            [
                "id" => "11",
                "name" => "Парвина",
                "surname" => "Мирахмедова",
                "patronymic" => "Кулиевна",
                "email" => "p.mirakhmedova@evolet.co.uk",
            ],
            [
                "id" => "12",
                "name" => "Сухроб",
                "surname" => "Мирзоев",
                "patronymic" => "Комилчонович",
                "email" => "mirzoev88@me.com",
            ],
            [
                "id" => "13",
                "name" => "Фирдавс",
                "surname" => "Сироджов",
                "patronymic" => "Махмадуллоевич",
                "email" => "mdsirojov@yahoo.com",
            ],
            [
                "id" => "14",
                "name" => "Фаррух",
                "surname" => "Каюмов",
                "patronymic" => "Саъдуллоевич",
                "email" => "farrukh.kayumov@evolet.co.uk",
            ],
            [
                "id" => "15",
                "name" => "Фариз",
                "surname" => "Мирзоев",
                "patronymic" => "Шералиевич",
                "email" => "farizmirzo@evolet.co.uk",
            ],
            [
                "id" => "16",
                "name" => "Бехрузи",
                "surname" => "Музаффар",
                "patronymic" => null,
                "email" => "behruz.muzaffar@outlook.com",
            ],
            [
                "id" => "17",
                "name" => "Мехроч",
                "surname" => "Хакимов",
                "patronymic" => "Зуфарович",
                "email" => "mkhakimov@evolet.co.uk",
            ],
            [
                "id" => "18",
                "name" => "Акмал",
                "surname" => "Шербадалов",
                "patronymic" => "Махмадуллоевич",
                "email" => "akmal.sherbadalov@evolet.co.uk",
            ],
            [
                "id" => "19",
                "name" => "Азиз",
                "surname" => "Носиров",
                "patronymic" => "Дилшодович",
                "email" => "azizjon1001@mail.ru",
            ],
            [
                "id" => "20",
                "name" => "Азим",
                "surname" => "Нажмуддинов",
                "patronymic" => "Акбарович",
                "email" => "azimjon-87@mail.ru",
            ],
            [
                "id" => "21",
                "name" => "Бободжон",
                "surname" => "Шарбатов",
                "patronymic" => "Фатохович",
                "email" => "sakr-al-bar.8080@mail.ru",
            ],
            [
                "id" => "22",
                "name" => "Нодира",
                "surname" => "Иноятова",
                "patronymic" => "Октябревна",
                "email" => "inonodira64@gmail.com",
            ],
            [
                "id" => "23",
                "name" => "Комила",
                "surname" => "Азимова",
                "patronymic" => "Джамшедовна",
                "email" => "azimovakamilla7@gmail.com",
            ],
            [
                "id" => "24",
                "name" => "Зайнаб",
                "surname" => "Сунатова",
                "patronymic" => "Назриевна",
                "email" => "zaynabsunatova1982@gmail.com",
            ],
            [
                "id" => "25",
                "name" => "Далер",
                "surname" => "Кодиров",
                "patronymic" => "Хайдарович",
                "email" => "daler.kodirov@evolet.co.uk",
            ],
            [
                "id" => "26",
                "name" => "Аниса",
                "surname" => "Мансурова",
                "patronymic" => "Мумтозовна",
                "email" => "anisa.pdd@evolet.co.uk",
            ],
            [
                "id" => "27",
                "name" => "Марьям",
                "surname" => "Зарипова",
                "patronymic" => "Рустамчоновна",
                "email" => "mimrzaripova@gmail.com",
            ],
            [
                "id" => "28",
                "name" => "Зебо",
                "surname" => "Каримова",
                "patronymic" => "Махмадуллоевна",
                "email" => "zebokarimova12@gmail.com",
            ],
            [
                "id" => "29",
                "name" => "Алим",
                "surname" => "Мунаваров",
                "patronymic" => "Сангмамадович",
                "email" => "alim.munavarov@evolet.co.uk",
            ],
            [
                "id" => "30",
                "name" => "Олимджон",
                "surname" => "Нурулоев",
                "patronymic" => "Сангинмуродович",
                "email" => "olimjon.nuruloev@evolet.co.uk",
            ],
            [
                "id" => "31",
                "name" => "Шахриёр",
                "surname" => "Пиров",
                "patronymic" => "Шарофович",
                "email" => "shahriyorp@icloud.com",
            ],
            [
                "id" => "32",
                "name" => "Абдукарим",
                "surname" => "Каримов",
                "patronymic" => "Абдухалимович",
                "email" => "karimov-abdukarim@inbox.ru",
            ],
            [
                "id" => "33",
                "name" => "Бехруз",
                "surname" => "Холов",
                "patronymic" => "Нуралиевич",
                "email" => "bekha95@bk.ru",
            ],
            [
                "id" => "34",
                "name" => "Манзура",
                "surname" => "Расулова",
                "patronymic" => "Мукимджоновна",
                "email" => "manya.rasulova@gmail.com",
            ],
            [
                "id" => "35",
                "name" => "Хумайро",
                "surname" => "Махмадалиева",
                "patronymic" => "Курбоналиевна",
                "email" => "ms.khumayro@list.ru",
            ],
            [
                "id" => "36",
                "name" => "Нурия",
                "surname" => "Маджидова",
                "patronymic" => "Рахматуллоевна",
                "email" => "nuriya_majidova@gmail.com",
            ],
            [
                "id" => "37",
                "name" => "Эхсон",
                "surname" => "Алифшоев",
                "patronymic" => "Олимшоевич",
                "email" => "ehson.alifshoev@gmail.com",
            ],
            [
                "id" => "38",
                "name" => "Садбарг",
                "surname" => "Валиева",
                "patronymic" => "Джумахоновна",
                "email" => "sadbargvalieva@gmail.com",
            ],
            [
                "id" => "39",
                "name" => "Кудратулло",
                "surname" => "Ашуров",
                "patronymic" => "Мансуруллоевич",
                "email" => "ashurov_kudratullo@gmail.com",
            ],
            [
                "id" => "40",
                "name" => "Умеджони",
                "surname" => "Неъмон",
                "patronymic" => "Мансуруллоевич",
                "email" => "umedjoni.nemon@gmail.com",
            ],
            [
                "id" => "41",
                "name" => "Омина",
                "surname" => "Шомирзоева",
                "patronymic" => "Исмоиловна",
                "email" => "ominamoh@mail.ru",
            ],
            [
                "id" => "42",
                "name" => "Акрам",
                "surname" => "Толибов",
                "patronymic" => "Сайфуллоевич",
                "email" => "akramtolibov@gmail.com",
            ],
            [
                "id" => "43",
                "name" => "Баходур",
                "surname" => "Нарзуллоев",
                "patronymic" => "Хусенович",
                "email" => "bahodur_narzulloevich@gmail.com",
            ],
            [
                "id" => "44",
                "name" => "Бобурхон",
                "surname" => "Нуридинов",
                "patronymic" => "Холматович",
                "email" => "boburjon_n@mail.ru",
            ],
            [
                "id" => "45",
                "name" => "Икром",
                "surname" => "Рахимов",
                "patronymic" => "Дилшодович",
                "email" => "ikromr04@gmail.com",
            ],
            [
                "id" => "46",
                "name" => "Денис",
                "surname" => "Ульянов",
                "patronymic" => "Владимирович",
                "email" => "dendenis83@gmail.com",
            ],
            [
                "id" => "47",
                "name" => "Анна",
                "surname" => "Мирзоева",
                "patronymic" => "Юрьевна",
                "email" => "mirzoeva.anna@evolet.co.uk",
            ],
            [
                "id" => "48",
                "name" => "Лола",
                "surname" => "Азимова",
                "patronymic" => "Джамшедовна",
                "email" => "azimovalola7@gmail.com",
            ],
            [
                "id" => "49",
                "name" => "Шерзод",
                "surname" => "Холматов",
                "patronymic" => "Тимурович",
                "email" => "sherkholmatov91@yandex.ru",
            ],
            [
                "id" => "50",
                "name" => "Фирдавс",
                "surname" => "Артиков",
                "patronymic" => "Мухаммадалиевич",
                "email" => "f.artykov@evolet.co.uk",
            ],
            [
                "id" => "51",
                "name" => "Комрон",
                "surname" => "Имомалиев",
                "patronymic" => "Хуршедович",
                "email" => "komron0309@gmail.com",
            ],
            [
                "id" => "52",
                "name" => "Таманно",
                "surname" => "Чумаева",
                "patronymic" => "Аличоновна",
                "email" => "t.j1898@mail.ru",
            ],
            [
                "id" => "53",
                "name" => "Миробиддин",
                "surname" => "Мирзоев",
                "patronymic" => "Сабохиддинович",
                "email" => "mirobiddin1993@gmail.com",
            ],
            [
                "id" => "54",
                "name" => "Шамсиддин",
                "surname" => "Мирзоев",
                "patronymic" => "Ниёзмахмадович",
                "email" => "shamsiddin.mirzoev2002@gmail.com",
            ],
            [
                "id" => "55",
                "name" => "Джамол",
                "surname" => "Джамолханов",
                "patronymic" => "Эхсонджонович",
                "email" => "jamol_jamolhanov@gmail.com",
            ],
            [
                "id" => "56",
                "name" => "Сабрина",
                "surname" => "Кадирова",
                "patronymic" => "Джамшедовна",
                "email" => "kadirova.sabrina@gmail.com",
            ],
            [
                "id" => "57",
                "name" => "Нурмухаммад",
                "surname" => "Забиров",
                "patronymic" => "Собирджонович",
                "email" => "zabirovns@mail.ru",
            ],
            [
                "id" => "58",
                "name" => "Амир",
                "surname" => "Арбобов",
                "patronymic" => "Алишерович",
                "email" => "amirarbobov@gmail.com",
            ],
            [
                "id" => "59",
                "name" => "Мадина",
                "surname" => "Зульфикорбекова",
                "patronymic" => "Бахтиёрова",
                "email" => "madina.bakhtiyor@mail.ru",
            ],
            [
                "id" => "60",
                "name" => "Мухаммадулло",
                "surname" => "Рахматуллоев",
                "patronymic" => "Нарзуллоевич",
                "email" => "muhammadullo_rahmatulloev@mail.ru",
            ],
            [
                "id" => "61",
                "name" => "Анора",
                "surname" => "Усмонзода",
                "patronymic" => "Джамшед",
                "email" => "anora.jamshed@mail.ru",
            ],
            [
                "id" => "62",
                "name" => "Муродчон",
                "surname" => "Бахромов",
                "patronymic" => "Шухратович",
                "email" => "murod.b@evolet.co.uk",
            ],
            [
                "id" => "63",
                "name" => "Фарходжон",
                "surname" => "Одилжонов",
                "patronymic" => "Исмоилжонович",
                "email" => "odiljonovfarhod@gmail.com",
            ],
            [
                "id" => "64",
                "name" => "Пайрав",
                "surname" => "Исоев",
                "patronymic" => "Умеджонович",
                "email" => "payravisoev22@gmail.com",
            ],
            [
                "id" => "65",
                "name" => "Ахдия",
                "surname" => "Мирзоева",
                "patronymic" => "Сабохиддиновна",
                "email" => "mirzoeva.a@evolet.co.uk",
            ],
            [
                "id" => "66",
                "name" => "Саидмумин",
                "surname" => "Ахмедов",
                "patronymic" => "Саидвалиевич",
                "email" => "saidmumin.a@evolet.co.uk",
            ],
            [
                "id" => "67",
                "name" => "Парвин",
                "surname" => "Набиев",
                "patronymic" => "Зохирович",
                "email" => "parvinnabiev3@gmail.com",
            ],
            [
                "id" => "68",
                "name" => "Камила",
                "surname" => "Аширова",
                "patronymic" => "Рустамовна",
                "email" => "kamilaashirova30@gmail.com",
            ],
            [
                "id" => "69",
                "name" => "Миркамол",
                "surname" => "Камолов",
                "patronymic" => "Джалолович",
                "email" => "kamolovmirkamol@outlook.com",
            ],
            [
                "id" => "70",
                "name" => "Хичрон",
                "surname" => "Сухробзода",
                "patronymic" => "Сухроб",
                "email" => "hijron.3535@gmail.com",
            ],
            [
                "id" => "71",
                "name" => "Нозилходжа",
                "surname" => "Рузиходжаев",
                "patronymic" => "Махмадович",
                "email" => "nozilhoja.r@evolet.co.uk",
            ],
            [
                "id" => "72",
                "name" => "Шодмон",
                "surname" => "Толибов",
                "patronymic" => "Махмадович",
                "email" => "tolibov6820@gmail.com",
            ],
            [
                "id" => "73",
                "name" => "Нилуфар",
                "surname" => "Шамсидинзода",
                "patronymic" => "Бобоназар",
                "email" => "ni.donism@gmail.com",
            ],
            [
                "id" => "74",
                "name" => "Юсуфджон",
                "surname" => "Саидов",
                "patronymic" => "Алишерович",
                "email" => "yusufjohnsaidov@gmail.com",
            ],
            [
                "id" => "75",
                "name" => "Нозанин",
                "surname" => "Абдурахмонова",
                "patronymic" => "Абдумаъруфовна",
                "email" => "raf.alex.n@gmail.com",
            ],
            [
                "id" => "76",
                "name" => "Мукаддас",
                "surname" => "Джабирова",
                "patronymic" => "Абдукодировна",
                "email" => "mndzhabirova@gmail.com",
            ],
            [
                "id" => "77",
                "name" => "Фирдавс",
                "surname" => "Асаншоев",
                "patronymic" => "Мирвалиевич",
                "email" => "fira.asanshoev@gmail.com",
            ],
            [
                "id" => "78",
                "name" => "Хусния",
                "surname" => "Файзуллоева",
                "patronymic" => "Зафаровна",
                "email" => "husniya112233@gmail.com",
            ],
            [
                "id" => "79",
                "name" => "Азиз",
                "surname" => "Носиров",
                "patronymic" => "Дилшодович",
                "email" => "aziz_nosirov@mail.ru",
            ],
            [
                "id" => "80",
                "name" => "Бехруз",
                "surname" => "Гулмамадов",
                "patronymic" => "Сафармамадович",
                "email" => "gulmamadov@mail.ru",
            ],
            [
                "id" => "81",
                "name" => "Осия",
                "surname" => "Мухаммадиева",
                "patronymic" => "Тулкунчоновна",
                "email" => "muhammadieva1999@gmail.com",
            ],
            [
                "id" => "82",
                "name" => "Амир",
                "surname" => "Акилов",
                "patronymic" => "Юсуфович",
                "email" => "akilovamir2000@gmail.com",
            ],
            [
                "id" => "83",
                "name" => "Мехроджиддин",
                "surname" => "Олимов",
                "patronymic" => "Рустамович",
                "email" => "mehroj.2411@icloud.com",
            ],
            [
                "id" => "84",
                "name" => "Ахмаджон",
                "surname" => "Давлатов",
                "patronymic" => "Одилджонович",
                "email" => "ddavlatovahmad@gmail.com",
            ],
            [
                "id" => "85",
                "name" => "Томирис",
                "surname" => "Раджабзода",
                "patronymic" => "Абдурахим",
                "email" => "rajabzade.tomiris@gmail.com",
            ],
            [
                "id" => "86",
                "name" => "Бахтиер",
                "surname" => "Рахимов",
                "patronymic" => "Мазбутджонович",
                "email" => "rahimov.2020@bk.ru",
            ],
            [
                "id" => "87",
                "name" => "Сафарали",
                "surname" => "Одиназода",
                "patronymic" => "Хукуматулло",
                "email" => "s.odinaeff@gmail.com",
            ],
            [
                "id" => "88",
                "name" => "Ахтам",
                "surname" => "Ситамзода",
                "patronymic" => "Сафарали",
                "email" => "sitamov07@gmail.com",
            ],
            [
                "id" => "89",
                "name" => "Фазлиддин",
                "surname" => "Бомуллоев",
                "patronymic" => "Далерович",
                "email" => "fazliddinbom2003@gmail.com",
            ],
            [
                "id" => "90",
                "name" => "Акбар",
                "surname" => "Сайфуллоев",
                "patronymic" => "Парвизович",
                "email" => "akbarjon.s@evolet.co.uk",
            ]
        ];

        foreach ($users as $user) {
            User::create([
                'name' => $user['name'],
                'surname' => $user['surname'],
                'patronymic' => $user['patronymic'],
                'email' => $user['email'],
                'password' => Str::random(8)
            ]);
        }
    }
}
